name: potentials
channels:
- conda-forge
dependencies:
- cmake
- python
- atomicrex =1.0.3
- runner =1.2
- pyiron_potentialfit =0.0.1
- pyiron_gpl =0.0.3
- pyiron_workflow =0.0.3
- pyiron-data
- nbgitpuller =1.2.0
- python-ace =0.2.8
- lammps =2023.08.02
- calphy =1.2.12
- iprpy-data
- sphinxdft >=2.7.0
- sphinxdft-data
- nglview
- numpy >=1.26.0
- pyscal
- pyscal3
- jupyterlab
- jupyter-book
- sqsgenerator
- pymatgen
- ipykernel
- runner
- ipympl
- ipywidgets
- matplotlib-base =3.8.0
- pyscal-rdf
- pydantic >=2.3.0
- randspg
- mp-api =0.37.5
- typing-extensions =4.8.0
- mpi4py =3.1.4
- pylammpsmpi =0.2.3
- pip:
    #- runnerase
    #- tensorflow <=2.7
    - pychromatic
